---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: 4343434

description: 

conditions:
  allOf:
    - property:
        name: stringProp
        operator: in-array
        operands:
            - '5454 '
