---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: ewewe

description: ddd

conditions:
  allOf:
    - property:
        name: stringProp
        operator: in-array
        operands:
            - ewewe
