---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: fff

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: stringProp
          operator: regex
          operands:
            - gfgfgf
    flagValue: false
