apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My standard workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  Job1:
    steps:
      - name: Say hello job1
        shell: sh
        run: |
          echo "Hello world from job1"
    runs-on:
      - rama-label-3
