---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: f1
flagType: boolean
description: ""
labels:
  - l1
  - l7
  - other
  - l3
  - l6
  - l4
  - l8
  - l5
  - some rrrr
  - l2

availableValues:
  - "true"
  - "false"

isPermanent: false
