---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: rererer
flagType: boolean
description: ""
labels:
  - l7
  - toto

availableValues:
  - "true"
  - "false"

isPermanent: false
